{{- range $tenantName, $tenantConfig := .Values.tenants }}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ $tenantConfig.jeager.name }}
  namespace: {{ $tenantConfig.jeager.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  channel: {{ $tenantConfig.jeager.channel }}
  installPlanApproval: {{ $tenantConfig.jeager.installPlanApproval }}
  name: {{ $tenantConfig.jeager.name }}
  source: {{ $tenantConfig.jeager.source }}
  sourceNamespace: {{ $tenantConfig.jeager.sourceNamespace }}
{{- end }}
