{{- range $tenantName, $tenantConfig := .Values.tenants }}
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: elasticsearch-operator-group
  namespace: {{ $tenantConfig.elasticSearch.namespace}}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
{{- end }}